alias ga 'git add'
alias gb 'git branch'
alias gc 'git commit'
alias gclean 'git clean -fd'
alias gco 'git checkout'
alias gcob 'git checkout -b'
alias gd 'git diff'
alias gdca 'git diff --cached'
alias gdt 'git difftool'
alias gf 'git fetch'
alias gl 'git pull'
alias glog 'git log --oneline --decorate --graph'
alias gp 'git push'
alias gpf 'git push --force-with-lease'
alias gr 'git rebase'
alias gri 'git rebase -i'
alias grim 'git rebase -i origin/master'
alias gst 'git status'
alias gwt 'git worktree'
alias groot "cd (git rev-parse --show-toplevel)"
