balias ga 'git add'
balias gb 'git branch'
balias gc 'git commit'
balias gclean 'git clean -fd'
balias gco 'git checkout'
balias gcob 'git checkout -b'
balias gd 'git diff'
balias gdca 'git diff --cached'
balias gdt 'git difftool'
balias gf 'git fetch'
balias gl 'git pull'
balias glog 'git log --oneline --decorate --graph'
balias gp 'git push'
balias gpf 'git push --force-with-lease'
balias gr 'git rebase'
balias gri 'git rebase -i'
balias grim 'git rebase -i origin/master'
balias gst 'git status'
balias gwt 'git worktree'
balias groot "cd (git rev-parse --show-toplevel)"
